.gitignore
src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt

This converts the external config file to json.
This allows for using proper lists.
The config should now look similar to this:
```json
{
"arisa": {
"credentials": {
"username": "arisa",
"password": "1234"
},
"issues": {
"projects": [
"MCTEST"
]
},
"modules": {
"attachment": {
"extensionBlacklist": [
"test"
]
}
}
}
}
```

Change to json config to allow for proper lists

---

src/main/kotlin/io/github/mojira/arisa/infrastructure/Jira.kt
src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt

I just ran a test in MCTEST with the crash module active and noticed 2 bugs.
1. The attachment's mimeType is not the extension, but something like `plain/Text` and thus does not equal `.txt` for crash reports.
2. The `resolveAs` method did not work. This was because the API expects a JSON object containing a key with either `id` or `name` and a respective value. The used library does not know which of these it is given, so it must be specified.

Fixes crash module extension detection and resolveAs method

---

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt

Whoops.
Totally not my fault 😛

fix crash module using whitelist from empty module

---

src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt

This is a very minor change that just tweaks the bot footer to make it a bit more readable, and in general look a bit nicer. Here's an example:
Before:
After:

Tweak bot footer slightly to make it more readable

---

arisa.json
src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt

Filter projects after caching the issues to avoid having to call jira multiple times
Cache without filtering by projects, then filter on each module

Filter projects after caching

---

arisa.json
src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
src/main/kotlin/io/github/mojira/arisa/modules/Module.kt
src/main/kotlin/io/github/mojira/arisa/modules/ResolveTrashModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/ResolveTrashTest.kt

Resolve TRASHed tickets automatically to invalid if not done so
Fixes #58
Filters to only TRASH and to only Unresolved in arisa.json, does a double check that its a TRASH ticket inside the module and then closes as invalid

Resolve trash to invalid automagically

---

src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/Cache.kt

When running a modified version of arisa to update the linked field, I noticed that only a handful of issues are updated.
The issue was, that the jira search client is paginated and only returns a page of 50 issues.
This especially causes issues after a downtime when trying to catch up again.
Utilizing the iterator, the SearchResult provides, the lib takes care of that and you actually do iterate over all issues.
Using the lib's iterator (and converting it to a sequence)
Furthermore, it is possible to set the maxResults of a search query. Default is 50, and it is capped at 1,000. In this PR, I changed it to 1,000, and to reduce outgoing traffic more, it is also possible to specify fields and expand fields in the search request directly, so it is not needed to query every single issue …

Iterate over all issues

---

src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt

Currently, the ModuleExecutor tries to get all issues that match the query at once, which may lead to java allocating too much memory, or the collecting of issues taking extremely long.
This PR changes it, so that the module executor only tries to process a smaller amount of issues at once
The ModuleExecutor now executes all modules in a while loop, as long as at least one jql query did not yet return all pages. Per iteration, the starting index is increased.
The constant `MAX_RESULTS` determine how big the requested pages are.
While running this, I have noticed it still being quite slow when issues with a higher amount of data are returned.
Setting breakpoints in the code and seeing how long each step takes, it seems like Arisa's modules take most of the processing time. As far as I can …

Process issues pagewise

---

src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt

Arisa gets stuck because `result.start` is 0, when we overflow. With multiple jql queries, arisa gets stuck at the end, because one of them has results after the first page. This fixes this.

Fix arisa getting stuck

---

arisa.json

Very minor change, but I've noticed a bunch of `.url` tickets attached to tickets on the tracker. These files usually are not, but can be harmful, but they are not useful at all. Therefore Arisa should probably remove them.

Add .url to attachment extension blacklist

---

src/main/kotlin/io/github/mojira/arisa/modules/HideImpostorsModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/HideImpostorsTest.kt

Fix #130 
The name now must match the regex `\[(?:\p{L}|\p{N}|\s)+\]\s.+` for the module to trigger.

Change author name rquirements for HideImpostors

---

src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/Jira.kt

Fixes #129
Explicitly filling the optional parameter in the partially.

Fix HideImpostors failing when envoking the restrict comment method

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/module-request.md
.github/pull_request_template.md

The issue presets in particular are more annoying than helpful and I find myself (and others) just deleting everything and writing issues without a preset most of the time
This rewrites all issue presets to what I think would be more useful.
It also removes any descriptive texts of what you should put were, as I expect people who submit issues to a project related to a bug tracker, were mostly mods and helpers of said tracker post, to be knowing what they are doing.
With this, I hope not having to delete anything for most issues when trying to create one.

Better presets

---

src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/modules/EmptyModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/LanguageModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/Module.kt
src/main/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/EmptyModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/LanguageModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModuleTest.kt

Resolves #144 
This mostly just removes the filter from `ModuleExecutor`.
Most modules have not been changed. Here is a list of all modules and my thoughts:
- **Attachment**: Should always see all issues and remove malicious attachments everywhere.
- **Crash**: I don't see a problem here. If an issue is reopened from AR, it should obviously be checked here. I don't really see this module mistriggering, and if it does, an issue should be opened.
- **Empty**: Empty has been changed to only resolve issues that were created after the last run.
- **FutureVersion**: Don't see it being relevant here.
- **HideImpostors**: Should always trigger on issues were impostors post.
- **KeepPrivate**: Should always trigger on all issues that are to be kept private.
- **Language**: LanguageModule has been …

Allow Modules to see isues that have been resolved or reopened as last action.

---

arisa.json
src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
src/main/kotlin/io/github/mojira/arisa/modules/ConfirmParentModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/ConfirmParentModuleTest.kt

Resolve #123
Added a new ConfirmParentModule which will set the Confirmation Status of tickets whose Linked is greater than `linkedThreshold` and Confirmation Status exists in `confirmationStatusWhitelist` to the value specified in `targetConfirmationStatus`.

Add ConfirmParentModule

---

arisa.json
src/main/kotlin/io/github/mojira/arisa/modules/ReplaceTextModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/ReplaceTextModuleTest.kt

Fix #159.
Added a zero-width negative lookahead assertation for any numbers (in case the Regex engine goes back several characters so the assertation could pass), `?`, `#`, and `/` (also in case the Regex engine goes back).

No longer replace links with query parameters

---

src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/modules/Module.kt
src/main/kotlin/io/github/mojira/arisa/modules/TransferVersionsModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/TransferVersionsTest.kt

Fixes #166
This slightly refactors the LinkedIssue of TransferVersions. Instead of a function that returns a linked issue, the linked issue is now directly available with all fields that are present in the issue link.
LinkedIssue now includes a function that returns a list of versions, as versions are not available in the issue object that is present in the link.
TransferVersions is pretty messy in the ModuleRegistry, we should look into moving mapping functions into a separate file, as was already suggested by urielsalis in #125

Require status "Open" or "Reopened" for parents in TransferVersions

---

src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt

Fix Arisa searching issues caused by extra '}' in jql string

---

src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/modules/UpdateLinkedModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/UpdateLinkedModuleTest.kt

This fixes UpdateLinkedModule only updating when a link was added, and not when one was removed.
Additionally, the module would count all links that were ever added, even if they were removed again.
The module now also receives the old value for all changes, so that it can also know when a link was removed.

Also consider changes caused by removed links in UpdateLinkedModule

---

src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt

Currently, Arisa is trying to transfer versions, even if the parent already has the version added
This was caused by the module registry mapping to the version id in one instance and the version name in another instance.
Both instances now correctly map to the version id.

Fix arisa trying to add versions in transfer versions that are already added

---

arisa.json
src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt

Fix #180 
This removes date fields such as CHK and Triaged Time from the config.
They are not that important anyways and a bit harder to parse, which would probably need some specific code just for date fields inside of the module.
Double fields are now first cast to int, so that the field matches the entry from the changelog.

Disable module for date fields, fix for double

---

arisa.json

The module was activated again in #194, but #184 still happens.

Disable RemoveTriagedMeqs module

---

arisa.json

Reverts mojira/arisa-kt#196
An old screen was running which was likely causing issues (see #197).
Should be good now, as this is literally the version now that was running fine for weeks.

Revert "Disable RemoveTriagedMeqs module"

---

src/main/kotlin/io/github/mojira/arisa/domain/Link.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt
src/test/kotlin/io/github/mojira/arisa/modules/TransferVersionsModuleTest.kt

Fix #211 
Link just threw an UnsupportedOperationException in the remove function for some reason.

Fix Link throwing UnsupportedOperation when attempting to remove it

---

arisa.json
src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/modules/KeepPrivateModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/KeepPrivateModuleTest.kt

Fix #226 
KeepPrivate module will no longer comment if the security level hasn't been
changed since the ticket was marked by the private tag.

Make KeepPrivate only comment when necessary

---

src/main/kotlin/io/github/mojira/arisa/modules/RemoveNonStaffMeqsModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/RemoveNonStaffMeqsModuleTest.kt

Fix RemoveNonStaffMeqs not restricting comments.
Change `update` to `restrict`.

Fix RemoveNonStaffMeqs not restricting comments

---

arisa.json

Try fixing #142... again...
Statistics of known false positives on tickets that only has English texts (different from #122).
| Ticket     | Summary                                                 | Description                                                                                                                                     | Summary Length | Description Length | Total Length | Note                                                                     |
| ---------- | ------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------- | -------------- | ------------------ | ------------ | …

Double lengthThreshold of Language

---

src/main/kotlin/io/github/mojira/arisa/domain/Version.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt
src/main/kotlin/io/github/mojira/arisa/modules/TransferVersionsModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/TransferVersionsModuleTest.kt

Fix #250.
Only transfer versions that has a non-`null` `releaseDate`.

Support null releaseDate of versions

---

arisa.json
src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/modules/FutureVersionModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/FutureVersionModuleTest.kt

Fixes #228 
Resolve issues as awaiting response after removing the future version. Includes a message telling the user why
For some reason this module doesn't work in MCTEST, probably on the versions check. We might want to ask them to mark one of the versions as released

Resolve as awaiting response when removing future version

---

src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt

Fixes TransferFields throwing errors, caused by getFullIssue not containing all fields
get all fields in getIssue

get all fields in getFullIssue

---

src/main/kotlin/io/github/mojira/arisa/modules/RemoveNonStaffMeqsModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/RemoveNonStaffMeqsModuleTest.kt

Fix #283.
Simply added `global-moderators` to the list of allowed groups.
Make groups configurable. Not really necessary though since these groups shouldn't really change.

Add global-moderators to staff groups in RemoveNonStaffMeqsModule

---

src/main/kotlin/io/github/mojira/arisa/infrastructure/HelperMessages.kt
src/test/kotlin/io/github/mojira/arisa/infrastructure/HelperMessagesTest.kt

Fix #282 by expecting variables to contain other variables.
When resolving a variable, the replacement text is thrown again into the `resolveVariables` function in order to find and replace other variables. This happens up to 10 times. Depending on how complicated the variables are, this might lead to a significant speed decrease, but I expect the helper message variables to be rather sane.
I don't think variables should become even more complicated lol

Handle variables containing other variables

---

build.gradle.kts
src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/test/kotlin/io/github/mojira/arisa/ModuleRegistryTest.kt

Tests the module registry to make sure we dont forget a module
Check that we have a registered module per config
Check that we have a registered module per module class
Check that the configs are used by only 1 module to prevent us forgetting from using the correct config

Add test for Module Registry

---

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/Cache.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt

Fix issue changes made by modules other than the first one aren't applied.
Changes made by modules other than the first one are ignored because the `IssueUpdateContextCache` is cleared in `executeModule`.
This PR moves the process of adding new context to the cache to the returned `Lazy`, so that even if the cache is cleared the context will always be added back to the cache, therefore changes made by other modules won't be ignored
Merge #299 after this PR is merged.

Fix issue changes aren't applied

---

src/main/kotlin/io/github/mojira/arisa/domain/ChangeLogItem.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt
src/main/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/FutureVersionModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/RevokeConfirmationModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/UpdateLinkedModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/FutureVersionModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/KeepPrivateModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/RevokeConfirmationModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/UpdateLinkedModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/utils/MockDomain.kt

Resolve #307.
By checking the change log to see if the change is made by an user with the `staff` group.

No longer remove future versions added by staff

---

src/main/kotlin/io/github/mojira/arisa/modules/RemoveIdenticalLinkModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/TransferLinksModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/RemoveIdenticalLinkModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/TransferLinksModuleTest.kt

Fix #302
By ignoring the direction (`outwards`) of `Relates` links.

Fix not removing identical relates links

---

src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt

Fix not logging exceptions when failed
Fix not performing `otherOperations` after other changes.

Fix applying issue changes

---

arisa.json

The Linked field has been added to more projects (see [STAFF-389](https://bugs.mojang.com/browse/STAFF-389)), thus the module should be enabled for more projects
Change json config

Enable linked module for more projects

---

arisa.json
src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt

This fixes some issues the crash module had so far. The idea comes from #360, although this does not require the crash report to have been uploaded by the reporter.
The crash module now requires the following:
* One crash report was uploaded since the last run.
* All of the uploaded crash reports are invalid (so either a dupe or modded). It does not matter when those were uploaded.
Since the first point already requires a recent report and the 2nd one requires all reports to be accessible, I removed the configurable option of maxAttachmentAge.

Improve crash module

---

src/main/kotlin/io/github/mojira/arisa/modules/AbstractTransferFieldModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/TransferLinksModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/TransferVersionsModuleTest.kt

Fix #362 
Transfer modules now only transer to newly added links, so changes made after the link was added will not be considered.

Only transfer to newly added parents

---

arisa.json

See #376 and https://discordapp.com/channels/647810384031645728/663488001346764805/734097599556091945.
I am disabling that module for now, until this has been discussed with more people from the team.
Disable the module

Disable MissingCrashModule

---

src/main/kotlin/io/github/mojira/arisa/modules/ConfirmParentModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/Helpers.kt
src/test/kotlin/io/github/mojira/arisa/modules/ConfirmParentModuleTest.kt

Fix #378.
By checking the duplicated links of the parent ticket until an error occurs or the amount of duplicates is above the threshold (`3`).

Fix being able to confirm user's own tickets

---

arisa.json
src/main/kotlin/io/github/mojira/arisa/domain/Attachment.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt
src/main/kotlin/io/github/mojira/arisa/modules/AttachmentModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/CommandModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/PurgeAttachmentCommand.kt
src/test/kotlin/io/github/mojira/arisa/modules/CommandModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/commands/PurgeAttachmentCommandTest.kt
src/test/kotlin/io/github/mojira/arisa/utils/MockDomain.kt

Fix #306.
By adding a new `ARISA_PURGE_ATTACHMENT <start ID> [<stop ID>]` command.

Add ARISA_PURGE_ATTACHMENT command

---

arisa.json
src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
src/main/kotlin/io/github/mojira/arisa/modules/RemoveVersionModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/RemoveVersionModuleTest.kt

Closes #406 
Allows volunteers to add affected versions to resolved tickets, but removes them if added by a normal user

Remove extra added versions to resolved tickets by users

---

arisa.json

'Nova' is considered a pirated launcher. This causes reports mentioning Huawei Nova mobile devices to be automatically invalidated. This may be a big issue, unless I'm missing something and just using one of those devices really means that you're pirating the game. Additionally, as stated in #435, using the word 'nova' in a report triggers both the piracy module and the language module at once, which causes Arisa to make an empty comment. This will fix the main cause of that issue.
Example ticket: https://bugs.mojang.com/browse/MCPE-101708
Remove nova from arisa.json.

Remove 'nova' from pirated launcher list

---

arisa.json

sh, command, and cmd are file types that essentially serve the same purpose as bat files, so they should be removed from tickets automatically as well.

Add sh, command, and cmd to extension blacklist

---

src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt

In createLink when you try to link a non-existing ticket with outwards = false, the exception is not caught into context cache and I'm not sure whether this kind of exception is handled well
Catch any exceptions that happen when getContext is used, and add them into cache

Fix exception in createLink

---

src/main/kotlin/io/github/mojira/arisa/modules/CommandModule.kt

To not have the warning each time you try to commit CommandModule.kt
Add casting for the OperationNotNeededModuleResponse.left() into an Either with the same types as the invoke's return type (as it has the Right type set)

Fix the warning about inferring the type of the return value of bind() to Nothing

---

arisa.json

Add .dylib and .bundle files to the excluded list, which may be malicious and have been attached to tickets recently. (see https://discord.com/channels/647810384031645728/647810384622911490/768120496306389043)
Add these extensions to the excluded extensions list.

Add dylib and bundle files to the excluded list

---

arisa.json

Fixes mojira#480.
Add .iso and .smi to the disallow list, as these file types are similar to dmg files and may be malicious.
Add these extensions to the arisa.json file.

Add .img and .smi to disallow list

---

arisa.json

Fixes #483. Like Jack McKalling said in a comment in that issue, focusing on only the allowed file types may be beneficial in the future. However, I don't think this should be changed without further discussion (I don't know if discussion is already being done internally).
This pull request blocks .saver and .definition files, which both can contain malicious code.
Add these file extensions to `arisa.json`.

Add .saver and .definition files to disallow list

---

src/main/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModuleTest.kt

Fix #301
Add a function to check for the keepAR message and don't comment again if one exists

Only allow the keep AR message once per ticket

---

README.md

The link to the license in README.md is to a file named LICENSE, which is non-existent. The correct file is LICENSE.md.
Correct the name of this file within the link in the README.md file.

Fix License link in README.md

---

src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/PrivacyModuleTest.kt

When a access token is detected in a attachment, make the ticket private
Check for "--accessToken ey"

Make access token private

---

arisa.json
src/test/kotlin/io/github/mojira/arisa/infrastructure/HelperMessagesTest.kt

Projects MCAPI and MCE (Minecraft Earth) do not exist anymore. This pull request removes references to them.

Remove references to removed projects MCAPI and MCE

---

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt
src/main/kotlin/io/github/mojira/arisa/modules/CommandModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/RemoveUserCommand.kt

Remove all comments from certain users by issuing a command
When command is triggered, look for the name in the arguments, call the jira api using the credentials to get their status, find all comments they ever did and set them to staff only
Tested in TRASH-26834, needs unit tests, I ran out of time, but should work. Needs cleanup and tests

Remove all comments from user

---

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
src/main/kotlin/io/github/mojira/arisa/modules/CommandModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/RemoveUserCommand.kt

Fix fetching a user's comments if the user has a space in their username

Fix fetching user comments with spaces in user name

---

src/main/kotlin/io/github/mojira/arisa/modules/commands/RemoveUserCommand.kt

Jira's inconsistency causes the username to be incorrect with underlines, this will fix that

Fix underlines in user names for Arisa command

---

arisa.json
src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
src/main/kotlin/io/github/mojira/arisa/modules/RemoveSpamModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/RemoveSpamModuleTest.kt

Remove spam following certain patterns as soon as it's posted.
Monitor new comments and check if a regex matches at least `threshold` times.
Hopefully keep as is. If needed, add more patterns to config.
Could be expanded to ticket creation if needed (although we have bulk resolve for that so not as critical).

Add RemoveSpamModule

---

src/main/kotlin/io/github/mojira/arisa/modules/TransferVersionsModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/TransferVersionsModuleTest.kt

Remove the check in TransferVersionsModule that prevented any versions older than the oldest version on the parent ticket from being transferred over to the parent ticket. It was introduced because of #229.
This was more of a hinderance than a help. See also `/archives/G0NM0QG14/p1610724495034400` where this was discussed.
I simply removed all the code related to this check.
N/A

TransferVersionsModule: Remove release date check

---

src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt

It appears the regex syntax has a peculiarity where `[…-]` matches the `-` literally (while `[…-…]` represents a range). When #403 added the `_` it accidentially converted `-` into ranges which match a bunch of characters which are not allowed by [RFC 952](https://tools.ietf.org/html/rfc952).

Fix wrong e-mail regex of PrivacyModule

---

build.gradle.kts

Stop depending on jcenter and bintray
Remove dependency from detekt by excluding, use new version of klaxon which is in maven central

Fix #536 - Stop depending on jcenter and bintray

---

src/main/kotlin/io/github/mojira/arisa/modules/PiracyModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/PiracyModuleTest.kt

Fix #551
Use empty string by default if input is null
N/A

Fix #551 by using empty string if input is null

---

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
src/main/resources/logback.xml

It's currently not easy to test a specific module on Mojira without the fear of something going wrong large-scale.
- Option to only enable selected modules
- Option to only monitor selected tickets
- Option to not update last run file
- No longer need to specify dandelion key
- Rewritten module registration code
These options can be set in the `arisa.yml` file locally so that they aren't pushed to remove.
I've added some `log.debug` method calls. I'm not sure how the logs are currently configured and if the production logs have debug level enabled. If they have, how can these loggers be changed to INFO debug level?

Add more debug options

---

src/main/kotlin/io/github/mojira/arisa/modules/AttachmentModule.kt

Add a restricted comment with information about the removed attachment whenever AttachmentModule executes

Comment with information about removed attachment

---

.github/workflows/gradle-wrapper-validation.yml

Fix triggering the validate action twice for the same commit.
https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662

Fix triggering GitHub action twice

---

config/config.yml
src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/ArisaConfig.kt
src/main/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/RemoveUserCommand.kt
src/test/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModuleTest.kt

Use the forward duplicate message when the parent was created after the child 

---

src/main/kotlin/io/github/mojira/arisa/modules/AttachmentModule.kt

This was originally copied directly from the Duplicate Message module, and I noticed that I left some asterisks that were used in formatting the ticket names, but are useless in the Attachment Module.

Remove asterisks from the attachment details

---

config/config.yml

Fix #435 
The Piracy message is only available in MC and MCL, which causes Arisa to leave an empty comment when posting in a different project

Prevent Arisa from leaving empty comments

---

src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/ArisaConfig.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/RemoveUserCommand.kt

The RemoveUserCommand didn't work because apparently Java classes are able to return non-null types even if they can be null and thus I wasn't required to check whether things returned from the rcarz Issue class were null?
Null-sanitize default functions in `RemoveUserCommand`
Also I disabled logging of returned issues by default. It's spamming the log quite a bit.

Null-sanitize calls to rcarz Issue class

---

src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/modules/CommandModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/CommandExceptions.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/CommandSource.kt
src/test/kotlin/io/github/mojira/arisa/modules/CommandModuleTest.kt

Fix #533
Read each line as a singular command!
Also I improved feedback and formatting a bit to make it more intuitive (which was also kinda required for preventing the bot from executing a comment twice if lastRun isn't updated correctly for whatever reason)
You can see how it looks here: https://bugs.mojang.com/browse/MC-193399 (obviously Arisa's username will appear instead of mine
Run all the commands!!!

Accept multiple commands in a single comment

---

src/main/kotlin/io/github/mojira/arisa/domain/User.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/JqlUtils.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt
src/main/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/RemoveContentCommand.kt
src/test/kotlin/io/github/mojira/arisa/infrastructure/JqlUtilsTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/RemoveVersionModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/utils/MockDomain.kt

Don't reopen an AR bug report if the commenter both:
* doesn't have any comments older than 24 hours AND
* doesn't have any non-trash bug reports older than 24 hours
Also fixes #608 along the way. This also technically makes #600 redundant.
Note that some code here is untested (notably the `Mappers.kt` changes). However that's going to be refactored anyway so I didn't bother.
I added a new method to `User` that is called and mocked
N/A

ReopenAwaitingModule: Don't reopen if commenter is a new user

---

src/main/kotlin/io/github/mojira/arisa/modules/RemoveIdenticalLinkModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/RemoveIdenticalLinkModuleTest.kt

Fix #487.
By always removing the outwards link belonging to the smaller ticket key.

Fix removing both Relates links

---

.gitignore
build.gradle.kts
src/main/kotlin/io/github/mojira/arisa/infrastructure/AttachmentUtils.kt
src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt

- Download mappings only once
- Save crashes to a temp directory in case deleting fails
- Check for zip slip

General improvements to crash module

---

.gitignore
src/main/kotlin/io/github/mojira/arisa/domain/Issue.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt
src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/utils/MockDomain.kt

Follow-up for #641
Delete the temporary folder containing the crash report once the uploaded finished.

Delete temporary crashes directory after upload

---

config/config.yml

This causes false positives due to its vague nature as a number, see https://bugs.mojang.com/browse/MC-225612 (private, see environment).

Remove 1.0.8 from piracy module

---

src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt
src/main/kotlin/io/github/mojira/arisa/modules/ThumbnailModule.kt

The previous solution of using JDK's Http Client did not work for private issues and comments because it did not have the necessary session token.
Use JiraClient's Apache HttpClient instance for requesting the attachment content stream, since that has the necessary token set.

Use JiraClient's HttpClient for opening attachment stream

---

src/main/kotlin/io/github/mojira/arisa/infrastructure/LanguageDetectionApi.kt
src/main/kotlin/io/github/mojira/arisa/modules/Helpers.kt

Reverts the LanguageDetectionApi.kt changes done by 02bca459eaf707efd6819ca727c57c0e9ebac2cf. For some reason the requests did not work properly and the server complained about missing token value.
E.g. when using an invalid token the error response was:
```
{"error":true,"status":403,"code":"error.notAllowed","message":"token param is missing","data":{"parameter":"token"}}
```
Now with the reverted changes the error response is:
```
{"error":true,"status":401,"code":"error.invalidParameter","message":"no such token 'abcdef'","data":{"parameter":"token"}}
```

Revert to using HttpURLConnection for language API call

---

README.md

See https://dandelion.eu/accounts/tos/, "Attribution"
> When using Dandelion, or content generated via a Dandelion's API, for any purpose with a Free Plan, you agree to:
> Provide a clickable hyperlink to http://dandelion.eu/ with the text "Powered by Dandelion API" within your website or application

Add link to language API site to README

---

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/HelperMessages.kt

Improve fetching, parsing and storing of helper messages. Most importantly:
- Fix the following logic being wrong, writing the helper messages before they have been deserialized:
https://github.com/mojira/arisa-kt/blob/02bca459eaf707efd6819ca727c57c0e9ebac2cf/src/main/kotlin/io/github/mojira/arisa/infrastructure/HelperMessages.kt#L135-L136
- Fix no exceptions being logged / start not failing without helper messages; previously `updateHelperMessages(...)` returned an `Either<Error, ...>` but the caller never inspected the result. Now instead throw exceptions instead of using `Either`.

Improve helper messages fetching

---

src/main/kotlin/io/github/mojira/arisa/infrastructure/LanguageDetectionApi.kt
src/main/kotlin/io/github/mojira/arisa/modules/Helpers.kt
src/main/kotlin/io/github/mojira/arisa/modules/LanguageModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/ThumbnailModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/LanguageModuleTest.kt

Improve logging of language API requests.
Depends on #649
When logging when calling the language API:
- Log quota information, see https://dandelion.eu/docs/api/#api-response-headers
- Log error response body
:warning: This might reveal sensitive information; for example when the token is invalid it looks like the reponse contains the token. Maybe that is not desired?
Also changes the `LanguageDetectionApi.kt` function to throw exceptions instead of using `Either`. Previously the language module would siltently ignore `Either.left`, without logging the exception. Additionally switches from `Error` to `IllegalArgumentException` / `IOException`; `Error` is usually only used for really critical exceptions, see [documentation](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/l …

Improve language detection API logging

---

config/config.yml

Helpers usually don't want a ticket to be reopened when they post a comment on an AR tickets. Thus they should probably be ignored.
Add `helper` to `blacklistedRoles` config
N/A

ReopenAwaitingModule: Ignore comments from helpers

---

build.gradle.kts
src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/AttachmentUtils.kt
src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt

Now that mc-crash-lib is in maven central, use that version :D

Update mc-crash-lib to maven central version

---

src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt

Stop privating reports when crash report is added (matches `java.base@16.0.1`)
Force matching a single letter in the TLD

Remove numbers from domains and prevent other false positives with the privacy module

---

.github/pull_request_template.md
docs/Commands.md
docs/Modules.md

As mentioned in https://github.com/mojira/arisa-kt/issues/286#issuecomment-634299807 and internally it is easier to keep documentation files in the repository up to date than using the Wiki.
Additionally this allows creating pull requests for the documentation.
Remove the Wiki pages.

Convert Wiki to repository docs

---

config/config.yml
docs/Modules.md
src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/ArisaConfig.kt
src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/PrivacyModuleTest.kt

Fix #673
Add a `sensitiveFileNames` `List<String>` config value and specify the launcher file names in the config.
See #663

Make PrivacyModule detect sensitive launcher files

---

config/config.yml
src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/LanguageDetectionApi.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/ArisaConfig.kt

As mentioned by @urielsalis internally the current quota logging for the language API is too spammy because it is logged for every request.
Define a `apiQuotaWarningThreshold` config entry. When the quota units become equal to or lower than this value a warning will be logged once.
Therefore no further messages are logged while the quota remains that low, and only once it was reset and again became lower than the threshold a warning will be logged again.

Use threshold for logging language API quota warning

---

build.gradle.kts

Upgrade mc-crash-lib to get the latest bug fixes and features, most notably deobfuscation for pre-release crash reports has been fixed.

Upgrade mc-crash-lib

---

config/config.yml

Fix #678
Remove it from the automatic duplicate module

Fix #678 - Remove OutOfMemory from duplicate module due to false positives

---

src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt

Fix #680
Append deobf at the start

Fix #680 - Append deobf to the start instead of the end of attachment name

---

src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/AttachmentUtils.kt
src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt

See https://github.com/mojira/arisa-kt/pull/681#discussion_r645991308
In AttachmentUtils, attachments uploaded by Arisa are ignored straight away.
I went ahead and refactored the CrashModule a little bit more as well.

Improve infinite loop protection in CrashModule

---

build.gradle.kts

Update mc-crash-lib to support Java 16 modules
Adds new regex in mc-crash-lib

Update mc-crash-lib to support Java 16 modules

---

build.gradle.kts

See https://github.com/napstr/logback-discord-appender/pull/3
Probably has no impact since Arisa does not exit if the config is correct, but in case the configuration is incorrect or an uncaught exception causes the main loop to stop it will now also cause the complete program to exit.

Update logback-discord-appender dependency

---

src/main/kotlin/io/github/mojira/arisa/modules/ThumbnailModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/ThumbnailModuleTest.kt

Now and then the description of reports contains multiple embedded images without space between them, e.g. `!test.png!!test.png!`. Currently the regex pattern used by the ThumbnailModule is not matching these.
Adjust regex pattern to match these images.
Note: When shown as thumbnail Jira does not add any padding between the images so this might look confusing. However, changing the module to also add a line break might change the intended formatting and would also complicate the logic (since it would have to detect multiple embedded images directly next to each other).

Change thumbnail regex to match multiple embedded images without space

---

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt

Oversight I made when writing #690
After a successful relog Arisa should probably also wait for the normal sleep interval.

Add delay after successful relog

---

src/main/kotlin/io/github/mojira/arisa/modules/ThumbnailModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/ThumbnailModuleTest.kt

Previously, the thumbnail module would allow `!` and `\n` to be part of file names. That's obviously not legal
Try to understand the regex and put something there that solves the issue
I also removed one case from a test that's actually not illegal.

Fix ThumbnailModule allowing ! and \n to be part of file names

---

src/main/kotlin/io/github/mojira/arisa/modules/ThumbnailModule.kt

In #702 I accidentally wrongificated the documentation for the regex in ThumbnailModule. This PR dewrongificates the documentation again.
Press backspace a bunch

Fix ThumbnailModule regex documentation

---

src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/PrivacyModuleTest.kt

braintree transaction IDs currently seem to consist of 8 digits or letters, `PrivacyModule`'s regex pattern currently does not detect this.
Adjust regex pattern. This should not result in an increase of false positives since the pattern explicitly requires the prefix `braintree:`.

Fix PrivacyModule not detecting braintree transaction IDs

---

src/main/kotlin/io/github/mojira/arisa/modules/Helpers.kt
src/main/kotlin/io/github/mojira/arisa/modules/RevokeConfirmationModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/RevokeConfirmationModuleTest.kt

When a non-volunteer removes the confirmation status, it is not readded by the revoke confirmation module.

Re-add empty confirmation

---

config/config.yml
src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
src/main/kotlin/io/github/mojira/arisa/ConfigService.kt
src/main/kotlin/io/github/mojira/arisa/ExecutionService.kt
src/main/kotlin/io/github/mojira/arisa/ExecutionTimeframe.kt
src/main/kotlin/io/github/mojira/arisa/Executor.kt
src/main/kotlin/io/github/mojira/arisa/HelperMessageUpdateService.kt
src/main/kotlin/io/github/mojira/arisa/JiraConnectionService.kt
src/main/kotlin/io/github/mojira/arisa/LastRun.kt
src/main/kotlin/io/github/mojira/arisa/WebhookService.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/ArisaConfig.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt
src/main/kotlin/io/github/mojira/arisa/registry/DelayedModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/registry/InstantModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/registry/LinkedModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/registry/ModuleRegistry.kt
src/test/kotlin/io/github/mojira/arisa/ExecutionTimeframeTest.kt
src/test/kotlin/io/github/mojira/arisa/ExecutorTest.kt
src/test/kotlin/io/github/mojira/arisa/LastRunTest.kt

`ArisaMain` got messier and messier, so it's time for some spring cleaning, innit?
This turned out to be a bigger task than I expected.
This PR refactors `ArisaMain` by splitting it up into smaller pieces. Most notably:
* `JiraConnectionService` is responsible for connecting to Jira, and reconnecting if something goes wrong
* `HelperMessageUpdateService` is simply responsible to update the helper messages if they haven't been updated in a while. Simple.
* `LastRun` is responsible for keeping track of the previous run, saving it to the file, and reading it from the file when the bot starts initially.
* `ExecutionTimeframe` existed previously inside of `ModuleRegistry`, now it's its own class and handles everything in regard to the time frame in which the bot searches for updated tickets.
* …

Refactor ArisaMain

---

config/config.yml

These are windows configuration files which may be dangerous towards users if they download them. I don't think removing these will be frequent but I've just removed one from a bug report so I thought I'd make this PR: https://bugs.mojang.com/browse/MCL-18792

Remove .sys attachments from bug reports

---

src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt

The last regex in the privacy module can cause false positives in launcher logs.
Example (note the `5865-5e24-84d9-f4b7` part):
```
[Info: 2021-07-16 21:24:45.7786953: ClientStarter.cpp(1071)] Java argument:-Djava.library.path=C:\Users\<>\AppData\Roaming\.minecraft\bin\5865-5e24-84d9-f4b7
```
This commit removes that regex.

Remove a regex causing false positives

---

docs/Commands.md
src/main/kotlin/io/github/mojira/arisa/domain/Issue.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/CommandDispatcher.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/CommandExceptions.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/FixedCommand.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/arguments/GreedyStringWithTrailingFlagArgumentType.kt
src/test/kotlin/io/github/mojira/arisa/modules/commands/FixedCommandTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/commands/arguments/GreedyStringWithTrailingFlagArgumentTypeTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/commands/arguments/LinkListArgumentTypeTest.kt
src/test/kotlin/io/github/mojira/arisa/utils/MockDomain.kt

Improves `FixedCommand` argument validation by failing if _any_ of the affected versions is the same or newer than the fix version.
This reimplements the changes of #721.
However, when a trailing `force` literal is present this check is skipped, allowing to set a fix version even when erroneously added affected versions exist which cannot be removed anymore (because they are archived), e.g.:
```
$ARISA_FIXED 12w34a force
```
@Pokechu22, that should solve the issue you mentioned, right?
Uses a custom Brigadier argument type which acts like a _greedy string_ but allows a trailing _flag_; for the `FixedCommand` that is `force`. This still allows easily using version names containing spaces without having to quote them.
In theory this could cause issues when a version name ends with " force", …

Reject version for FixedCommand if same or older than any affected version

---

src/main/kotlin/io/github/mojira/arisa/infrastructure/HelperMessages.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt
src/main/kotlin/io/github/mojira/arisa/modules/AttachmentModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/CommandModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/ListUserActivityCommand.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/RemoveContentCommand.kt
src/test/kotlin/io/github/mojira/arisa/infrastructure/HelperMessagesTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/AttachmentModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/CommandModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/commands/ListUserActivityCommandTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/commands/RemoveContentCommandTest.kt
src/test/kotlin/io/github/mojira/arisa/utils/MockDomain.kt

Sanitize user controlled arguments which are included in bot comments to prevent command injection.
- Specify a list of allowed characters, see `Functions.kt#sanitizeCommentArg`
- Make `CommandModule` ignore comments written by bot
Together with #671 we should have a single function testing whether an issue has a 'tag' comment, e.g. `MEQS_KEEP_PLATFORM`.
This function should ignore comments written by the bot to prevent tag injection.

Sanitize user controlled arguments in bot comments

---

config/config.yml
docs/Modules.md
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/ArisaConfig.kt
src/main/kotlin/io/github/mojira/arisa/modules/TransferVersionsModule.kt
src/main/kotlin/io/github/mojira/arisa/registry/InstantModuleRegistry.kt
src/test/kotlin/io/github/mojira/arisa/modules/TransferVersionsModuleTest.kt

In most cases launcher legacy version was selected erroneously by user, so it should not be transferred to the duplicated report.
This was originally raised by @dericksonmark.
Support specifying a list of Jira version IDs for `TransferVersionsModule` which should not be transferred. The `config.yml` currently only contains the version ID of MCL version "1.6.93 (legacy)".
@dericksonmark proposed adding a `ARISA_IGNORE_VERSION <version>` tag which can be added to a report to prevent Arisa from transferring that version. However, that might be a bit cumbersome especially since a large amount (or nearly all) reports with "1.6.93 (legacy)" have selected it erroneously.

Don't transfer launcher legacy version to duplicated report

---

config/config.yml
docs/Modules.md
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/ArisaConfig.kt
src/main/kotlin/io/github/mojira/arisa/modules/AffectedVersionMessageModule.kt
src/main/kotlin/io/github/mojira/arisa/registry/InstantModuleRegistry.kt
src/test/kotlin/io/github/mojira/arisa/modules/AffectedVersionMessageModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/RemoveSpamModuleTest.kt

🚧 Depends on https://github.com/mojira/helper-messages/pull/166
In most cases the legacy launcher version is erroneously selected. The message tells the user to verify that they are actually using the legacy launcher.
Adds `AffectedVersionMessageModule` which adds a message comment if a specific version is marked as affected.
The module is configured using a map from Jira version ID to message key.
The `config.yml` contains a mapping entry for "1.6.93 (legacy)" to the message added by https://github.com/mojira/helper-messages/pull/166

Add module for adding message when user selects legacy launcher version

---

src/main/kotlin/io/github/mojira/arisa/domain/Comment.kt
src/main/kotlin/io/github/mojira/arisa/domain/Version.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt
src/main/kotlin/io/github/mojira/arisa/modules/CommandModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/FixedCommand.kt
src/test/kotlin/io/github/mojira/arisa/modules/KeepPrivateModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/PrivateDuplicateModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/ReplaceTextModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/utils/MockDomain.kt

- Fix a `NullPointerException` for `FixedCommand` which occurred when the `releaseDate` of a version is `null`.
There are a few versions which, despite being released, have no release date.
- Improve command feedback for exceptions with `null` message (e.g. `NullPointerException`). Now if the message is `null` the string representation of the exception will be used as message.
- Add logging for command results. Apparently we did not have any logging (?). Now for successful execution an info message is logged and for execution failure an error with the exception is logged.
This should hopefully not cause too much spam in the log because commands are not used that often (?). The log output also includes the used command and the user who executed it.

Fix `NullPointerException` for FixedCommand

---

config/config.yml

Block JFR files as they contain access tokens
Add it to the extension blacklist

Make bug reports with attached JFR files private, as they can contain access tokens

---

config/config.yml
docs/Modules.md
src/main/kotlin/io/github/mojira/arisa/ConfigService.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/ArisaConfig.kt
src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt
src/main/kotlin/io/github/mojira/arisa/registry/InstantModuleRegistry.kt
src/test/kotlin/io/github/mojira/arisa/infrastructure/IntegrationTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/PrivacyModuleTest.kt

Refactor PrivacyModule (acts as a follow-up for #751).
Make config parsing stricter.
Refactors the PrivacyModule to:
- allow specifying sensitive text patterns in the config instead of hardcoding them
- support regex patterns for sensitive file names
Additionally the test class PrivacyModuleTest is refactored to cover more cases and to reuse test code for email address and sensitive text detection.
The config parsing has also been made stricter, requiring that all required entries are present and that no unknown entries exist.
:warning: Please verify that the local config used by Arisa does not have unknown / unused entries.

Refactor PrivacyModule

---

.gitignore
docs/Commands.md
docs/Modules.md
src/main/kotlin/io/github/mojira/arisa/ExecutionTimeframe.kt
src/main/kotlin/io/github/mojira/arisa/Executor.kt
src/main/kotlin/io/github/mojira/arisa/LastRun.kt
src/main/kotlin/io/github/mojira/arisa/LastRunFile.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/ArisaConfig.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt
src/main/kotlin/io/github/mojira/arisa/modules/CommandModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/Module.kt
src/main/kotlin/io/github/mojira/arisa/modules/ShadowbanModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/CommandDispatcher.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/ShadowbanCommand.kt
src/main/kotlin/io/github/mojira/arisa/registry/InstantModuleRegistry.kt
src/main/kotlin/io/github/mojira/arisa/registry/ModuleRegistry.kt
src/test/kotlin/io/github/mojira/arisa/ExecutionTimeframeTest.kt
src/test/kotlin/io/github/mojira/arisa/ExecutorTest.kt
src/test/kotlin/io/github/mojira/arisa/LastRunTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/CommandModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/ShadowbanModuleTest.kt

Add a shadowban command to revert all actions for a specific user, for a duration of 24 hours.
Save shadowbans in last run file. I've completely reworked the last run file on the occasion. Have a module that checks for any actions of shadowbanned users on any updated ticket, by looking it up in the last run file essentially. The command just adds the ban to the last run file.
See the commit messages of the individual commits for more information.
There are some shady things I did, please review thoroughly. If you have a better idea on how to solve the communication between command and last run file, feel free to provide suggestions. I felt like threading through the last run file just for this was a bit much.
General clean up.

Add shadowban command

---

config/config.yml

It appears there are more launcher files which contain potentially sensitive information. Reports with such files should be made private.

Add more sensitive launcher files

---

config/config.yml
docs/Modules.md
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/ArisaConfig.kt
src/main/kotlin/io/github/mojira/arisa/modules/RemoveSpamModule.kt
src/test/kotlin/io/github/mojira/arisa/modules/RemoveSpamModuleTest.kt

Add a new spam pattern + also check newly created bug reports for spam
If a bug report matches the spam patterns, it's put in the spam bin.
Also patterns have been hidden and need to be specified in the `local.yml` file now.

Scan newly created bug reports for spam

---

config/config.yml

Format removal message correctly with command prefix ($ARISA)
(Leaves the old one there as well just in case someone forgets the $ in front of it and to remove it in tags)

Format removal message correctly with command prefix

---

docs/Commands.md
src/main/kotlin/io/github/mojira/arisa/modules/commands/CommandDispatcher.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/PurgeAttachmentCommand.kt
src/test/kotlin/io/github/mojira/arisa/modules/commands/PurgeAttachmentCommandTest.kt

Fix #759.
By changing the syntax of the command from
```
$ARISA_PURGE_ATTACHMENT <username> [<minId> [<maxId>]]
```
to
```
$ARISA_PURGE_ATTACHMENT [from <minId>] [to <maxId>] [by <username>]
```
This makes all eight possible combinations of ways to filter attachments legal:
```
$ARISA_PURGE_ATTACHMENT                   // Remove all attachments from the report.
$ARISA_PURGE_ATTACHMENT by Annoying User  // Remove all attachments uploaded by "Annoying User" from the report.
$ARISA_PURGE_ATTACHMENT from 10000
$ARISA_PURGE_ATTACHMENT from 10000 by Annoying User
$ARISA_PURGE_ATTACHMENT from 10000 to 20000
$ARISA_PURGE_ATTACHMENT from 10000 to 20000 by Annoying User
$ARISA_PURGE_ATTACHMENT to 20000
$ARISA_PURGE_ATTACHMENT to 20000 by Annoying User
```

Fix range argument in $ARISA_PURGE_ATTACHMENT

---

build.gradle.kts

Fixes #764
Upgrades mc-crash-lib to the fixed version

Update mc-crash-lib to 2.0.7

---

docs/Modules.md
src/main/kotlin/io/github/mojira/arisa/modules/RevokePriorityModule.kt

Helpers are not able to set Mojang Priority, yet the RevokePriorityModule thinks they are. This causes issues
Remove helpers from privileged roles in RevokePriorityModule
N/A

RevokePriorityModule: Ignore helpers when determining correct Mojang Priority

---

config/config.yml

The RevokePriorityModule needs some more work and throws errors currently, so let's just disable it for now.

Disable RevokePriorityModule

---

config/config.yml
src/main/kotlin/io/github/mojira/arisa/domain/Attachment.kt
src/test/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModuleTest.kt

The JSON files in the `profilekeys` directory of the game installation directory contain RSA private keys used for authentication at
servers and for signing chat messages. Therefore they should be treated as sensitive.
- Update `sensitiveTextRegexes` in config
- Treat MIME types `application/json` (and `application/xml`) as text

Detect profilekeys attachments as sensitive

---

.github/workflows/pull-request-build.yml
.github/workflows/push-build-deploy.yml

- Renames the GitHub workflow files to express better what they are doing and in which situations they are running (feedback for better names is welcome though)
- Allow manual re-deployment; might be useful in certain situations, see a4156d76b192315686b17888e824e746884a7091
@violine1101, what was actually the context for that re-deployment?

Rename GitHub workflow files and allow manual triggering of deployment

---

build.gradle.kts

Fixes #783
Was apparently caused by a combination of optional dom4j dependencies not being declared as optional which were replacing the standard `SAXParserFactory`, and by recent logback changes which require features not supported by that `SAXParserFactory` implementation.
<details>
<summary>Full error output</summary>
```
ch.qos.logback.core.joran.spi.JoranException: Error during parser creation or parser configuration
at ch.qos.logback.core.joran.event.SaxEventRecorder.buildSaxParser(SaxEventRecorder.java:100)
at ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(SaxEventRecorder.java:62)
at ch.qos.logback.core.joran.GenericXMLConfigurator.populateSaxEventRecorder(GenericXMLConfigurator.java:178)
at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfi …
```

Fix logback failing to parse log config XML

---

src/main/resources/logback.xml

Newlines were showing up on Discord:
This PR fixes that issue by reverting the formatting change for that particular pattern.

Remove newline in Discord log pattern

---

build.gradle.kts

Update mc-crash-lib to latest version with forge logs

Update mc-crash-lib to latest version with forge logs

---

config/config.yml

Add the new Minecraft Legends (MCLG) project to Arisa.
Update the config -- to my knowledge no updates are needed anywhere else.
Note that MCLG uses a custom platform field, similar to Dungeons. I've not adjusted this yet and as such the platform modules are disabled for now.
Hope for the best and that things don't break.
Enable the platform modules for MCLG soon.

Add Minecraft Legends project

---

config/config.yml
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/ArisaConfig.kt
src/main/kotlin/io/github/mojira/arisa/modules/KeepPrivateModule.kt
src/main/kotlin/io/github/mojira/arisa/registry/InstantModuleRegistry.kt
src/test/kotlin/io/github/mojira/arisa/modules/KeepPrivateModuleTest.kt

Moving private bug reports to MCL would prompt Arisa to change their security level to an invalid one, making them inaccessible.
Changed the function for determining whether a bug report is public by checking if the security level is a private security level for _any_ project, not just the current one.
This is more of a bandaid solution, the actual problem likely lies somewhere deeper: Moving bug reports might actually cause some weird things to happen in regards to the data that Arisa receives.
So, further monitoring is necessary and potentially a better solution should be found at some point in the future - if we do not end up merging the MCL security level with the regular one anyway.

KeepPrivateModule: Special case for moving bug reports to MCL

---

config/config.yml
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/ArisaConfig.kt
src/main/kotlin/io/github/mojira/arisa/modules/KeepPrivateModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/LanguageModule.kt
src/main/kotlin/io/github/mojira/arisa/modules/PrivateDuplicateModule.kt
src/main/kotlin/io/github/mojira/arisa/registry/InstantModuleRegistry.kt
src/test/kotlin/io/github/mojira/arisa/modules/KeepPrivateModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/PrivateDuplicateModuleTest.kt

Some more issues with MCL security level happened
Always check for `securityLevel == null` or not. We don't have a dedicated "Public" security level anymore, if a bug report is public, its level is null.
N/A

Compare securityLevel to null for checking if issue is private

---

config/config.yml
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt

Arisa thought that MCL had the security level 10318, while it is actually 10502, as is specified in the config.
Apparently the config converts every key to lowercase, so convert the key to lowercase before retreiving it from the config. This might have been caused by some update to the konf library that we missed, not sure.
Change MCL on the bug tracker to use same security level as all the other projects.

Fix special security level retrieval

---

.github/dependabot.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/pull-request-build.yml
.github/workflows/push-build-deploy.yml

Updates GitHub actions used by the workflows, and configures Dependabot to also update GitHub actions.
The previous workflow executions were already causing warnings due to Node.js 16 actions being deprecated.
For the Gradle actions I changed the repository because https://github.com/gradle/actions is now the main repository for all Gradle-related actions. See also the README of https://github.com/gradle/wrapper-validation-action and https://github.com/gradle/gradle-build-action.
Note that I did not (and cannot) test the changes in `push-build-deploy.yml`, but I think they should be equivalent to the previous setup.

Update GitHub actions & enable Dependabot for them

---

src/main/kotlin/io/github/mojira/arisa/modules/commands/ListUserActivityCommand.kt
src/main/kotlin/io/github/mojira/arisa/modules/commands/RemoveContentCommand.kt
src/test/kotlin/io/github/mojira/arisa/modules/commands/ListUserActivityCommandTest.kt
src/test/kotlin/io/github/mojira/arisa/modules/commands/RemoveContentCommandTest.kt

Fixes #786
At least the `IllegalStateException` thrown by `initCause`; the reason why the activity search failed in the first place is a different issue (and I don't know the reason for that at the moment)
Use `Throwable#addSuppressed` instead of `Throwable#initCause`

Fix incorrect creation of `CommandSyntaxException` with cause

---

config/config.yml
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/ArisaConfig.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt

DO NOT MERGE
Make MCL use the same security level as the rest of the projects

Make MCL use the same security level as the rest of the projects

---

src/main/kotlin/io/github/mojira/arisa/apiclient/models/Version.kt
src/main/kotlin/io/github/mojira/arisa/apiclient/serializers/DateSerializer.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt
src/test/kotlin/io/github/mojira/arisa/apiclient/models/ProjectTest.kt
src/test/resources/responses/project-with-versions.json

Fixes (de)serialization bug where date format used on `Version` model was set to ISO-8601 instead of YYYY-MM-DD.
Add new serializer for affected fields. Test deserialization against example response.

fix: use yyyy-mm-dd serializer for version dates

---

.github/workflows/push-build-deploy.yml

Copy config when deploying, as rsync is copying it directly to the root directory instead of the config folder

Copy config on deploy

---

config/config.yml
src/main/kotlin/io/github/mojira/arisa/apiclient/JiraClient.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/ArisaConfig.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt
src/main/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModule.kt
src/main/kotlin/io/github/mojira/arisa/registry/InstantModuleRegistry.kt
src/test/kotlin/io/github/mojira/arisa/modules/privacy/PrivacyModuleTest.kt

- Logs error responses when client requests receives 4xx response,
- Adds config and logic in PrivacyModule to warn user when he posts comment with sensitive data,
- Fixes mapper to not stringify `null`,
- Fixes `restrictCommentToGroup` to not include mutually exclusive options.
Merge the PR in [helper-messages](https://github.com/mojira/helper-messages/pull/245) first, so new message panel is available.

fix: privacy module requests

---

src/main/kotlin/io/github/mojira/arisa/apiclient/JiraClient.kt
src/main/kotlin/io/github/mojira/arisa/apiclient/models/IssueFields.kt
src/main/kotlin/io/github/mojira/arisa/apiclient/models/Transitions.kt
src/main/kotlin/io/github/mojira/arisa/domain/User.kt
src/main/kotlin/io/github/mojira/arisa/domain/cloud/CloudIssue.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt
src/main/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModule.kt
src/main/kotlin/io/github/mojira/arisa/registry/InstantModuleRegistry.kt
src/test/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModuleTest.kt
src/test/kotlin/io/github/mojira/arisa/utils/MockCloudDomain.kt
src/test/kotlin/io/github/mojira/arisa/utils/MockDomain.kt

Re-registers the AwaitingResponse module, as it was adapted to the cloud API.
[reopen-by-reporter-comment.webm](https://github.com/user-attachments/assets/123dc4bf-e91a-4b8d-97ec-c8dd498ed847)
- Replace deprecated `name` attribute usages with `accountId`,
- Remove the logic of checking whether the user account is new (and accompanied tests),
- Port issue transition logic from old client.

fix: enable reopen awaiting module

---

src/test/kotlin/io/github/mojira/arisa/infrastructure/IntegrationTest.kt

Removes the [removed panel](https://github.com/mojira/helper-messages/commit/4c9c64224a07ec8d510040954502594d6d94fbad) from tests so they pass.

test: remove Unmarked private issue panel (helper-messages/4c9c642)

---

config/config.yml
config/local.template.yml
docs/ApiToken.md
src/main/kotlin/io/github/mojira/arisa/JiraConnectionService.kt
src/main/kotlin/io/github/mojira/arisa/apiclient/JiraClient.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/config/ArisaConfig.kt
src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt
src/test/kotlin/io/github/mojira/arisa/infrastructure/IntegrationTest.kt

Adds support for API Tokens with Scopes (both classic and granular). Deployment will require recreating [API Token](https://id.atlassian.com/manage-profile/security/api-tokens) with the scopes specified in `ApiToken.md`. I've added all used endpoints for quicker reference in the future if needed, as each has it's own scopes documented.
Additionally, using tokens with scopes requires using different URL to serve requests from. This URL requires using `cloudId` in requests. CloudID can be obtained by visiting https://mojira.atlassian.net/_edge/tenant_info
~~Improve logic for concatenating URL in `JiraClient.kt`.~~ Done.

feat: support api token with scopes

---

src/main/kotlin/io/github/mojira/arisa/Executor.kt
src/main/kotlin/io/github/mojira/arisa/apiclient/JiraClient.kt
src/main/kotlin/io/github/mojira/arisa/apiclient/models/SearchResults.kt
src/main/kotlin/io/github/mojira/arisa/apiclient/requestModels/JiraSearchRequest.kt
src/test/kotlin/io/github/mojira/arisa/ExecutorTest.kt

In https://developer.atlassian.com/changelog/#CHANGE-2046, Jira removed the endpoint we were using for search. Switch to the replacement

Move out of deprecated search endpoint
