mojira/arisa-kt

.github/workflows/gradle-wrapper-validation.yml
GitHub action which verifies that the `gradle-wrapper.jar` is legit.
See https://github.com/marketplace/actions/gradle-wrapper-validation
=> Add Gradle Wrapper Validation action

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/Jira.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt, src/main/kotlin/io/github/mojira/arisa/modules/EmptyModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/EmptyModuleTest.kt
=> Empty module

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
Same issue as ConfirmationStatus had.
=> fix getting Mojang Priority

src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt
=> Dont mark "Unknown" as modded

src/main/kotlin/io/github/mojira/arisa/modules/PiracyModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/PiracyModuleTest.kt
See https://github.com/mojira/arisa-kt/commit/9cce384da44760e3aed55b31183f37aea04546dc#r38319248
=> Fix piracy signatures using whitespaces not working

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt, src/main/kotlin/io/github/mojira/arisa/modules/RemoveNonStaffMeqsModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/RemoveTriagedMeqsModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/RemoveNonStaffMeqsModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/RemoveTriagedMeqsModuleTest.kt
=> Make tag removal comment change more meaningful

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/Jira.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt, src/main/kotlin/io/github/mojira/arisa/modules/KeepPrivateModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/KeepPrivateModuleTest.kt
=> Added keep private module

.gitignore, src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/Jira.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt, src/main/kotlin/io/github/mojira/arisa/modules/Module.kt, src/main/kotlin/io/github/mojira/arisa/modules/RevokeConfirmationModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/RevokeConfirmationTest.kt
=> add confirmation module

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
=> Remove shadow mode

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
=> Making messages more in line with helper messages

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt, src/main/kotlin/io/github/mojira/arisa/modules/HideImpostorsModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/HideImpostorsTest.kt
=> Hide comments where the display name has [] but they are not in the staff/mod/helper groups

arisa.json
=> Only run revoke confirmation in whitelisted projects

arisa.json
=> Remove extra ,

src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt, src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt
=> Fix non-null entries that should be nullaable

arisa.json
Keep private should probably run regardsless of resolution
I changed the config, Woooooo
=> Run keep private on all resolutions

arisa.json
Duplicates was missing from crash config
Add duplicates key to json config
=> add duplicates to json config

arisa.json
=> Disable revokeconfirmation in mctest

arisa.json, src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/Jira.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt, src/main/kotlin/io/github/mojira/arisa/modules/UpdateLinkedModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/UpdateLinkedModuleTest.kt
Adds a module that automatically updates the linked (#51)
Adds a new very cool module
=> add linked module

src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
=> Fix credentials

arisa.json
Fixes #120
Added an Italian entry to the language module's config.
=> Add Italian to the language module config

.github/workflows/push.yml
=> Use new deploy location

arisa.json, src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt, src/main/kotlin/io/github/mojira/arisa/modules/LanguageModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/LanguageModuleTest.kt
Resolve #142, hopefully.
By adding a new `lengthThreshold` config for LanguageModule.
Adjust the threshold as needed.
=> Add lengthThreshold for LanguageModule

arisa.json, src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt, src/main/kotlin/io/github/mojira/arisa/modules/ReplaceCommentModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/ReplaceCommentModuleTest.kt
Resolve #103.
By adding a new `ReplaceCommentModule`.
=> Add ReplaceCommentModule

arisa.json, src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/Jira.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt, src/main/kotlin/io/github/mojira/arisa/modules/Module.kt, src/main/kotlin/io/github/mojira/arisa/modules/ReplaceTextModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/ReplaceTextModuleTest.kt
Resolve #155.
Renamed the old `ReplaceCommentModule` to `ReplaceTextModule`, and added check for issue description.
=> Add replace text module

arisa.json
Disable module until #159 is fixed
=> disable-url-replacement

src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt, src/main/kotlin/io/github/mojira/arisa/modules/TransferVersionsModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/TransferVersionsTest.kt
Fixes #161 
Only consider parents from the same project
=> Fix TransferVersionModule attempting to add versions from a different project

arisa.json
=> Add missing config for transfer links module

arisa.json
=> Disable revoke fields

arisa.json
=> Remove Mojang Prio and ADO configs

arisa.json
Disable RemoveTriagedMeqs module until #184 is fixed.
Set whitelist to `[]`
=> Disable RemoveTriagedMeqs module (#184)

arisa.json
CrashModule is malfunctioning, see https://bugs.mojang.com/browse/MC-182391
=> Disable CrashModule

src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
=> Remove TODO comment (moved to #199)

.github/workflows/push.yml
Fixes #197
Kill all screens, and not just detached ones.
=> Kill all screens on deploy, even attached ones

.github/workflows/push.yml
=> Avoid piping excess lines from command respond into kill

.github/workflows/push.yml
=> Fix command name in workflow

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt, src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt, src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt, src/main/kotlin/io/github/mojira/arisa/domain/Attachment.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt, src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/EmptyModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/LanguageModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/Module.kt, src/main/kotlin/io/github/mojira/arisa/modules/ReplaceTextModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/ResolveTrashModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/AttachmentModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/EmptyModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/LanguageModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/ReplaceTextModuleTest.kt
=> Convert Long and Date to Instant everywhere

src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
=> Fix jql not converting lastRun to epoch millis

src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
=> Fix jql everywhere

src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
=> fix jql in update linked

src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt, src/main/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModuleTest.kt
Resolve #151.
Assert the last comment was created after last run.
=> Change ReopenAwaiting to assert comment was created after last run

src/main/kotlin/io/github/mojira/arisa/infrastructure/HelperMessages.kt
=> Use inputStream when fetching helper messages

arisa.json, src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/HelperMessages.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
Resolve #234.
Added a `arisa.helperMessages.updateInterval` setting.
=> Auto update helper messages

src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
Remove explicit name from module registry, instead use the class
Get the simple name from the class we use for config already
=> Remove explicit name from module registry, instead use the class

build.gradle.kts, src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt, src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt, src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/HelperMessages.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/LanguageDetectionApi.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/QueryCache.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt, src/main/kotlin/io/github/mojira/arisa/modules/AbstractTransferFieldModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/LanguageModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/Module.kt, src/main/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/RevokeConfirmationModule.kt
Fixes #198 
Add detekt and fix all issues that its marking
Be annoyed by it the same way we do for ktlint and remove it :P
=> Add detekt

.github/workflows/push.yml
=> Change to new host

src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt, src/main/kotlin/io/github/mojira/arisa/domain/Version.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt, src/main/kotlin/io/github/mojira/arisa/modules/AbstractTransferFieldModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/TransferVersionsModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/FutureVersionModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/TransferVersionsModuleTest.kt
Fix #229.
By checking the `releaseDate` of versions.
=> Fix tranferring old affected versions

src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt
=> Fix TransferVersions

src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt, src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
=> Add 'only' module setting

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/HelperMessages.kt, src/test/kotlin/io/github/mojira/arisa/infrastructure/HelperMessagesTest.kt, src/test/kotlin/io/github/mojira/arisa/infrastructure/IntegrationTest.kt
Test on build if arisa.json and helper-messages is valid
Fixes #148, #231
=> Add test for helper messages and arisa.json

arisa.json
=> Disable transfer versions

arisa.json
=> Revert "Disable transfer versions"

.github/workflows/gradle.yml
It's a bit anoyying that every push on draft pull request will trigger a build which will definitely fail
=> Don't test draft pull requests

src/main/kotlin/io/github/mojira/arisa/modules/LanguageModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/LanguageModuleTest.kt
Make LanguageModule not actually resolve tickets.
Comment them out.
=> Comment resolveAsInvalid out in LanguageModule

src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt
=> Register CHKModule

arisa.json, src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt, src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt, src/main/kotlin/io/github/mojira/arisa/domain/Issue.kt, src/main/kotlin/io/github/mojira/arisa/domain/Version.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt, src/main/kotlin/io/github/mojira/arisa/modules/CommandModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/Helpers.kt, src/main/kotlin/io/github/mojira/arisa/modules/HideImpostorsModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/Module.kt, src/main/kotlin/io/github/mojira/arisa/modules/commands/AddVersionCommand.kt, src/main/kotlin/io/github/mojira/arisa/modules/commands/Command.kt, src/main/kotlin/io/github/mojira/arisa/modules/commands/FixedCommand.kt, src/test/kotlin/io/github/mojira/arisa/modules/CommandModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/commands/AddVersionCommandTest.kt, src/test/kotlin/io/github/mojira/arisa/utils/MockDomain.kt
Fix #277,  #259, #280
Implement simple command parser and a command
- If we add more commands it might be worth creating a registry
- Fixed command, its a different issue
- It works as an example on how a test for module executor could look like :)
=> Add Add archived version command

src/main/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModuleTest.kt
=> Change DuplicateMessageModule to check the link time instead of the resolve time

src/main/kotlin/io/github/mojira/arisa/domain/User.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt, src/main/kotlin/io/github/mojira/arisa/modules/FutureVersionModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/FutureVersionModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/HideImpostorsModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/utils/MockDomain.kt
=> Remove future versions added on ticket creation

arisa.json
=> Enable FutureVersion on resolved tickets

arisa.json
Reverts mojira/arisa-kt#313
I totally forgot the fact that Arisa would resolve such a ticket as AR and that resolved tickets can't be resolved again 🤦
=> Revert "Enable FutureVersion on resolved tickets"

arisa.json, src/main/kotlin/io/github/mojira/arisa/domain/Issue.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt, src/main/kotlin/io/github/mojira/arisa/modules/LanguageModule.kt
Fix #60
Enable the language module fully per discussion with the other mods!
Translate more versions of the message in helper-messages
=> Resolve tickets in another language

src/main/kotlin/io/github/mojira/arisa/modules/CommandModule.kt
Limit add fixed version to only Mods
=> Limit add fixed version to only Mods

.github/workflows/gradle.yml, .github/workflows/push.yml
=> Optimize caching

arisa.json
https://bugs.mojang.com/browse/MC-190760
=> Disable piracy module on resolved tickets

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt, src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt
Separate Jira from Module Executor to allow easier testing
Implement tests from https://github.com/mojira/arisa-kt/issues/78
=> Separate Jira from Module Executor

.github/workflows/gradle.yml, .github/workflows/push.yml
=> Use better caching

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt, src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/Cache.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt
Resolve #190.
Keep a cache which stores the comments that are posted under each ticket in the last run.
=> Prevent from spamming comments

src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt
=> Use edit to update security level

arisa.json, src/test/kotlin/io/github/mojira/arisa/infrastructure/IntegrationTest.kt
Fix #303
Requires https://github.com/mojira/helper-messages/pull/82 to be merged first
=> Add message for Won't Fix

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt, src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt, src/test/kotlin/io/github/mojira/arisa/ModuleExecutorTest.kt
=> Module executor tests

src/main/kotlin/io/github/mojira/arisa/domain/User.kt, src/main/kotlin/io/github/mojira/arisa/modules/HideImpostorsModule.kt
=> fix exception during mapping when user name is null somehow

src/main/resources/logback.xml
=> Put logs as code blocks

src/main/resources/logback.xml
=> Wrap exceptions in a code block, use an inline code for regular messages

src/main/kotlin/io/github/mojira/arisa/modules/TransferLinksModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/TransferLinksModuleTest.kt
=> Fix TransferLinksModule linking issues to themselves

arisa.json
=> Remove MEQS_TRIAGE tag on triaged tickets

src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt, src/main/kotlin/io/github/mojira/arisa/domain/IssueUpdateContext.kt, src/main/kotlin/io/github/mojira/arisa/modules/TransferVersionsModule.kt
=> Fix re-run the ticket being updated instead of the one trigger the update

src/main/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModule.kt
Updates other than comments done by the reporter should also be able to reopen tickets in hard AR period
=> Fix not considering change log in hard AR period

.github/pull_request_template.md
This option is mostly used for reminding the person to update the Wiki
=> Add new check in pr template

src/main/kotlin/io/github/mojira/arisa/modules/FutureVersionModule.kt
=> No longer add latest version when don't have to

src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/PrivacyModuleTest.kt
=> Fix matching Emails in user mentions

src/main/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModuleTest.kt
=> Don't comment when an historical parent has been mentioned

src/main/kotlin/io/github/mojira/arisa/modules/CommandModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/commands/DeleteCommentsCommand.kt
=> Delete comments command

src/main/kotlin/io/github/mojira/arisa/modules/commands/DeleteCommentsCommand.kt
=> Add restriction

src/main/kotlin/io/github/mojira/arisa/modules/commands/DeleteCommentsCommand.kt
=> Sleep and async remove comments command

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt
=> Fix crashing when there's a final newline in lastRun

arisa.json, src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/PrivacyModuleTest.kt
=> Check emails containing underlines

src/main/kotlin/io/github/mojira/arisa/modules/ReplaceTextModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/ReplaceTextModuleTest.kt
=> No longer replace ticket IDs for edited texts

arisa.json, src/main/kotlin/io/github/mojira/arisa/modules/FutureVersionModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/FutureVersionModuleTest.kt
Fix #405 
(I hope I did this correctly, its my first pull request)
=> Check resolved tickets for future versions

arisa.json
Disable empty module for WEB
Set whitelist
=> Disable empty module for WEB

arisa.json
A bit of an oversight on my part, but it turns out I forgot two resolutions that we wouldn't want people adding affected versions to
=> Add missing resolutions to RemoveVersion

build.gradle.kts, src/main/kotlin/io/github/mojira/arisa/modules/CommandModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/ConfirmParentModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/LanguageModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/RevokeConfirmationModule.kt
Update the Kotlin version to the newly released 1.4
=> Update Kotlin to v1.4

src/main/kotlin/io/github/mojira/arisa/modules/Helpers.kt, src/test/kotlin/io/github/mojira/arisa/modules/HelpersTest.kt
Adding tests for functions in HelpersTest.kt
=> Tests for functions in HelpersTest.kt

src/main/kotlin/io/github/mojira/arisa/modules/ReplaceTextModule.kt
=> Fix Arisa breaking imgur embeds

src/main/kotlin/io/github/mojira/arisa/modules/KeepPlatformModule.kt
=> Potentially fix KeepPlatform

README.md
=> Add MC-Crash-Lib to dependencies

src/main/kotlin/io/github/mojira/arisa/modules/CommandModule.kt
=> Add author to command

src/main/kotlin/io/github/mojira/arisa/modules/CommandModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/AttachmentModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/CHKModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/CommandModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/CrashModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/EmptyModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/FutureVersionModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/HideImpostorsModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/LanguageModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/RemoveNonStaffMeqsModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/RemoveTriagedMeqsModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/RemoveVersionModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/ResolveTrashModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/UpdateLinkedModuleTest.kt
=> Fix tests not testing actual effects

arisa.json
Fixes #458. Additionally, blacklists ipa and app files.
=> Add .workflow, .app, and .ipa to extension blacklist

src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt
So you don't have to check the warnings each time you try to commit Functions.kt
Wrap those calls by `withContext(Dispatchers.IO)`
=> Fix inappropriate blocking method calls warnings

src/test/kotlin/io/github/mojira/arisa/modules/HelpersTest.kt
When moving getOrDefault I forgot to add tests for it
Added 3 tests for getOrDefault
=> Add tests for getOrDefault

src/main/kotlin/io/github/mojira/arisa/modules/FutureVersionModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/FutureVersionModuleTest.kt
Fix https://github.com/mojira/arisa-kt/issues/476 and add tests for adding versions
=> Fix Future Version module

arisa.json
Hide imposter comments on resolved tickets
=> Hide Imposters on resolved tickets

arisa.json, src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt, src/main/kotlin/io/github/mojira/arisa/modules/RemoveVersionModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/RemoveVersionModuleTest.kt
Closes #486
https://github.com/mojira/helper-messages/pull/127 for the message
=> Add a comment whenever a version is removed from a resolved ticket

arisa.json, src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt
Rename `whitelist` in module config to `projects`. See internal poll at \<internal communication tool>/archives/G01B5S71P8A/p1603299165086600
=> Rename whitelist to projects

arisa.json
=> Add REALMS to the confirmParentModule

arisa.json
=> Revert "Added .rar to extensionBlacklist"

src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt
=> Exempt Mojang from the privacy module

src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt
=> Exempt all moderators and helpers from the Privacy Module

arisa.json
=> Add .pptx to extension blacklist

arisa.json, src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt, src/main/kotlin/io/github/mojira/arisa/domain/Attachment.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/Arisa.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt, src/main/kotlin/io/github/mojira/arisa/modules/EliminatorModule.kt, src/test/kotlin/io/github/mojira/arisa/utils/MockDomain.kt
=> Add eliminator module

src/main/kotlin/io/github/mojira/arisa/modules/EliminatorModule.kt
=> Fix not removing attachments properly

src/main/kotlin/io/github/mojira/arisa/modules/commands/RemoveUserCommand.kt
=> Don't replace comment's content when removing a user

src/main/kotlin/io/github/mojira/arisa/modules/commands/RemoveUserCommand.kt
=> Fix space encoding

arisa.json
=> Fix indents in arisa.json

src/main/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/ReopenAwaitingModuleTest.kt
Previously the condition for reopening an awaiting response bug report was:
```kotlin
comments.none(::isKeepARTag) && (
(
!onlyOp && (
isSoftAR ||
validChangeLog.isNotEmpty()
)
) ||
validComments.any { it.author.name == reporter?.name }
)
```
(formatted for better readability)
which meant that if `onlyOp` is true, the bug report can only be reopened by the reporter commenting on the bug report, but not by updating it.
- Clean up formatting of reopen condition (and comment it)
- Add more unit tests for ARISA_REOPEN_OP
We should probably split up the unit test files at some point in the future and make the test cases more clearly labeled / structured. The `ReopenAwaitingModuleTest` class is pretty messy currently.
=> Fix ARISA_REOPEN_OP preventing reopening by report update

src/main/kotlin/io/github/mojira/arisa/modules/AttachmentModule.kt
=> Read attachment details correctly before commenting

.github/workflows/push.yml
Previously the `config.yml` file would be saved inside of the root directory instead of inside `config`
Upload the entire `config` folder, in case we add something there later
N/A
=> Fix config upload location

.github/workflows/push.yml
Exclude `local.yml` from being synced with the repo upon deployment
=> Prevent local.yml from being removed when deploying

src/main/resources/logback.xml
Currently the logging files are saved in the root directory instead of a separate folder
Changed the logging folder and logging file names.
Additional changes:
- Use plain text instead of HTML
- Save 14 days of logs
- Remove unneeded info from log (thread, logger)
- We're currently only logging on a single thread and a single logger, so we don't need to log which thread and logger we're using
- I plan to get rid of the separate `LanguageModule` logger along with #553. For now it should be obvious what the log message is from.
Make error logging actually useful (#553)
=> Fix logging

src/main/kotlin/io/github/mojira/arisa/modules/commands/RemoveUserCommand.kt
=> Fix for exclamation points in username

src/main/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModule.kt
=> Fix NPE in getForwardResolvedOrNot

src/main/kotlin/io/github/mojira/arisa/modules/commands/FixCapitalizationCommand.kt
=> Small fixes for capitalization regex

src/main/kotlin/io/github/mojira/arisa/modules/commands/FixCapitalizationCommand.kt, src/test/kotlin/io/github/mojira/arisa/modules/commands/FixCapitalizationCommandTest.kt
=> Allow exceptions in the fix capitalization command

src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt
=> Stop seeds from being privated

src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt
See https://github.com/mojira/arisa-kt/pull/573#discussion_r584856141
=> Another regex fix

src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt
Fix #575
Ignore attachments on changelog as we are checking them individually
=> Ignore attachments on changelog

src/main/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModuleTest.kt
=> Only get comments created by volunteers in the DuplicateMessageModule

src/main/kotlin/io/github/mojira/arisa/modules/RemoveVersionModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/RemoveVersionModuleTest.kt
Fix #601 
Don't remove the final version with the RemoveVersion module
=> Fix errors when trying to empty the affected versions field

src/main/kotlin/io/github/mojira/arisa/modules/AttachmentModule.kt
=> Reformat attachment details command to be more readable

config/config.yml, src/main/kotlin/io/github/mojira/arisa/ModuleRegistry.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/config/ArisaConfig.kt, src/main/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/commands/CommandDispatcher.kt, src/main/kotlin/io/github/mojira/arisa/modules/commands/RemoveContentCommand.kt, src/test/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/commands/RemoveContentCommandTest.kt
=> Rename 'ARISA_NO_DUPLICATE_MESSAGE' and 'ARISA_REMOVE_USER'

src/main/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModule.kt, src/test/kotlin/io/github/mojira/arisa/infrastructure/HelperMessagesTest.kt
Fix some small issues that cause warnings to appear while compiling
=> Make compiler happy

src/main/kotlin/io/github/mojira/arisa/modules/AttachmentModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/AttachmentModuleTest.kt
=> Fix attachment module comment details appearing blank

src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt
=> Fix crash module

src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt, src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt
=> Fix arisa spam

config/config.yml
"Xbox One" was renamed to "Xbox"
=> Correct changed platform name

src/main/kotlin/io/github/mojira/arisa/modules/UpdateLinkedModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/UpdateLinkedModuleTest.kt
Fixes #426
If linked is empty, set to 0
=> Set linked to 0 if empty

src/main/kotlin/io/github/mojira/arisa/modules/MultiplePlatformsModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/MultiplePlatformsModuleTest.kt
Fix #630
Check changelog of duplicates to make sure the link is new
=> Only get new duplicates in the Multiple Platforms Module

src/main/kotlin/io/github/mojira/arisa/modules/MultiplePlatformsModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/MultiplePlatformsModuleTest.kt
=> Fix error when updating Dungeons Platform in MultiplePlatform

src/main/kotlin/io/github/mojira/arisa/modules/KeepPlatformModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/MultiplePlatformsModule.kt
=> Change === to ==

build.gradle.kts, src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt
Update Detekt plugin to a newer version.
Ideally we should also update the ktlint plugin, but it looks like the new version has a different formatting style and finds a lot of violations.
=> Update Detekt plugin

README.md
=> Center README logo and description / fix #653

src/main/kotlin/io/github/mojira/arisa/infrastructure/LanguageDetectionApi.kt
Potentially fix 403 errors
https://stackoverflow.com/questions/3869372/java-io-ioexception-server-returned-http-response-code-403-for-url and https://stackoverflow.com/questions/16826345/why-do-i-get-a-403-error-when-i-try-open-a-url
I followed these two answers, which I hopefully did right.
=> Set user-agent for language api request

src/main/kotlin/io/github/mojira/arisa/infrastructure/LanguageDetectionApi.kt
=> Correct application type

src/main/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModuleTest.kt
=> Use the normal duplicate comment instead of private if the reporter is the same

src/main/kotlin/io/github/mojira/arisa/modules/commands/CommandDispatcher.kt, src/main/kotlin/io/github/mojira/arisa/modules/commands/CommandExceptions.kt, src/main/kotlin/io/github/mojira/arisa/modules/commands/MakePrivateCommand.kt, src/test/kotlin/io/github/mojira/arisa/modules/commands/FixCapitalizationCommandTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/commands/MakePrivateCommandTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/commands/ReopenCommandTest.kt
=> Add command for helpers to set tickets to private

build.gradle.kts
=> Upgrade mc-crash-lib to support lambdas

src/main/kotlin/io/github/mojira/arisa/Executor.kt, src/test/kotlin/io/github/mojira/arisa/ExecutorTest.kt
=> Executor: Don't retry a ticket again if it failed in the last run

.github/workflows/gradle.yml
=> Build: Use latest version of gradle-command-action

src/main/kotlin/io/github/mojira/arisa/modules/commands/CommandExceptions.kt, src/main/kotlin/io/github/mojira/arisa/modules/commands/FixedCommand.kt, src/test/kotlin/io/github/mojira/arisa/modules/commands/FixedCommandTest.kt
=> Make sure fixed command version was released after all affected versions

src/main/kotlin/io/github/mojira/arisa/modules/commands/CommandExceptions.kt, src/main/kotlin/io/github/mojira/arisa/modules/commands/FixedCommand.kt, src/test/kotlin/io/github/mojira/arisa/modules/commands/FixedCommandTest.kt
https://github.com/mojira/arisa-kt/issues/696#issuecomment-879188249
=> Only check first affected version in fixed command

docs/Modules.md, src/main/kotlin/io/github/mojira/arisa/modules/FutureVersionModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/FutureVersionModuleTest.kt
=> Switch Future Version to resolving as Invalid

src/main/kotlin/io/github/mojira/arisa/ArisaMain.kt, src/main/kotlin/io/github/mojira/arisa/ExecutionTimeframe.kt, src/main/kotlin/io/github/mojira/arisa/JiraConnectionService.kt, src/main/kotlin/io/github/mojira/arisa/registry/DelayedModuleRegistry.kt, src/main/kotlin/io/github/mojira/arisa/registry/InstantModuleRegistry.kt, src/main/kotlin/io/github/mojira/arisa/registry/LinkedModuleRegistry.kt, src/test/kotlin/io/github/mojira/arisa/ExecutionTimeframeTest.kt
Performs the refactoring mentioned in the review comments of https://github.com/mojira/arisa-kt/pull/701#pullrequestreview-702983583.
Note that some of my review comments were incorrect, therefore I did not implement these changes (and updated the review comments).
=> Perform follow-up refactoring for ArisaMain.kt changes

docs/Modules.md, src/main/kotlin/io/github/mojira/arisa/modules/FutureVersionModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/FutureVersionModuleTest.kt
Switch the Future version module to resolving as AR again (basically, reverts #725). I think this should work.
=> Switch Future Version to resolving as AR

config/config.yml, src/main/kotlin/io/github/mojira/arisa/modules/commands/CommandExceptions.kt, src/main/kotlin/io/github/mojira/arisa/modules/commands/ListUserActivityCommand.kt, src/main/kotlin/io/github/mojira/arisa/modules/commands/RemoveContentCommand.kt, src/test/kotlin/io/github/mojira/arisa/modules/commands/ListUserActivityCommandTest.kt
No major changes, just adding some more diagnostics to errors that we receive frequently and also fixed some minor bugs along the way.
N/A
Better diagnostics all across the board!!!
=> Add more details to command error messages and fix minor issues

docs/Commands.md
Make it clear what should be put for some greedy string arguments.
=> Note greedy string arguments in docs

docs/Modules.md
Adjusts module links and names in `Modules.md` after the changes done by #756.
=> Fix outdated links and update module name in Modules.md

.github/workflows/gradle.yml
Some of our actions were out of date or non-existant in the gradle command action, so I've updated
Updated `actions/setup-java` and `actions/checkout` to v3, and used `gradle/gradle-command-action`. Sorry about the newlines, on mobile lol
N/A
=> Improve actions

.github/workflows/push.yml
#771 but for the push workflow
See #771 
N/A
=> I forgot push workflow

.github/workflows/push.yml
Deploy is failing right now, because I forgot `distribution: temurin` :P
=> Set setup-java distribution to temurin

src/main/kotlin/io/github/mojira/arisa/ModuleExecutor.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/HelperMessages.kt, src/main/kotlin/io/github/mojira/arisa/modules/AbstractTransferFieldModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/CHKModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/DuplicateMessageModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/FutureVersionModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/Helpers.kt, src/main/kotlin/io/github/mojira/arisa/modules/KeepPlatformModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/RemoveIdenticalLinkModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/RemoveVersionModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/TransferLinksModule.kt, src/main/kotlin/io/github/mojira/arisa/modules/commands/FixCapitalizationCommand.kt, src/main/kotlin/io/github/mojira/arisa/modules/commands/arguments/EnumArgumentType.kt, src/main/kotlin/io/github/mojira/arisa/registry/InstantModuleRegistry.kt, src/main/kotlin/io/github/mojira/arisa/registry/ModuleRegistry.kt, src/test/kotlin/io/github/mojira/arisa/modules/MultiplePlatformsModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/RemoveVersionModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/commands/arguments/EnumArgumentTypeTest.kt
Fixes some deprecation warnings and cleans up imports.
=> Fix warnings and clean up imports

gradle/wrapper/gradle-wrapper.properties
=> Update Gradle wrapper version

docs/Commands.md, docs/Modules.md, src/main/kotlin/io/github/mojira/arisa/modules/KeepPrivateModule.kt, src/test/kotlin/io/github/mojira/arisa/modules/HelpersTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/RemoveSpamModuleTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/commands/AddLinksCommandTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/commands/DeleteCommentsCommandTest.kt, src/test/kotlin/io/github/mojira/arisa/modules/commands/DeleteLinksCommandTest.kt
Follow-up for #779
Fixes some cases of bad line wrapping in the documentation and makes the tests more compact again.
=> Improve formatting

.github/workflows/pull-request-build.yml
For faster execution(using the cache)!
=> Disable clean in PR builds

.editorconfig, src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Functions.kt, src/main/kotlin/io/github/mojira/arisa/modules/Helpers.kt
=> Add some extra logging using ugly reflection hacks

.github/workflows/gradle-wrapper-validation.yml, .github/workflows/pull-request-build.yml, .github/workflows/push-build-deploy.yml, build.gradle.kts
Switches from JDK 11 to JDK 17; @urielsalis mentioned to me in a private message that the server is running JDK 17 now.
=> Switch to JDK 17

src/main/kotlin/io/github/mojira/arisa/Executor.kt, src/main/kotlin/io/github/mojira/arisa/infrastructure/jira/Mappers.kt
=> Correctly map comments from anonymous users

src/main/kotlin/io/github/mojira/arisa/Executor.kt
=> Lower max results to 50

src/main/kotlin/io/github/mojira/arisa/ExecutionTimeframe.kt, src/test/kotlin/io/github/mojira/arisa/ExecutionTimeframeTest.kt
=> During migration, only look at new tickets instead of updated ones

src/main/kotlin/io/github/mojira/arisa/Executor.kt
=> Revert "Lower max results to 50"

src/main/kotlin/io/github/mojira/arisa/apiclient/JiraClient.kt, src/main/kotlin/io/github/mojira/arisa/apiclient/requestModels/JiraSearchRequest.kt
=> Use comma separated string instead of list
